### ISSUE TITLE
Bad Address 

### ISSUE THREAD

**Issue by OGKevin** [gpenverne/putio-mount#7]
Hey there,

When I try to access a file mounted with your Library I keep getting the following error: `: Bad address`

Any ideas what might be going on here?

**Comment by gpenverne** [comment]
Did you try with "PutioMount.set_config('use_mp4', False)" ?
Did you clone the repo or install with pip?

**Comment by OGKevin** [comment]
Yes with `use_mp4: false` in the config file. I've cloned it and installed it via setup tools. Might have been a conflict with py3 🤷‍♂️. I've installed it now in its own env and it seems to work fine now.

I appreciate this tool! I seem to be running into https://superuser.com/questions/529923/webdav-davfs2-input-output-error when I manually mount the webdav. This tool seems to work like a charm 🙏 .

**Comment by OGKevin** [comment]
Hmm false alarm, same error again `:  Bad address`

**Comment by OGKevin** [comment]
Hmm could it be firewall related maybe ?

**Comment by gpenverne** [comment]
I updated the lib this morning.

In the README I added a line to help to debug:
edit PutioMount/__init__.py to change: FUSE(PutioMounter(), mount_point, nothreads=False, foreground=False,**{'allow_other': True}) with FUSE(PutioMounter(), mount_point, nothreads=False, foreground=True,**{'allow_other': True})

It will run the lib in foreground and will show you the errors

**Comment by OGKevin** [comment]
Traceback: 

```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "build/bdist.linux-x86_64/egg/fuse.py", line 583, in read
    offset, fh)
  File "build/bdist.linux-x86_64/egg/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/plex/putio-mount/PutioMount/__init__.py", line 250, in read
    return downloader.read(offset, length, fileUrl, path)
  File "/home/plex/putio-mount/PutioMount/__init__.py", line 312, in read
    packet = self._get_packet(offset, length, url, path)
  File "/home/plex/putio-mount/PutioMount/__init__.py", line 302, in _get_packet
    clean_old_files()
  File "/home/plex/putio-mount/PutioMount/__init__.py", line 334, in clean_old_files
    if os.stat(f).st_atime < now - config.cache_expiration and os.path.isfile(f):
AttributeError: 'dict' object has no attribute 'cache_expiration'
```

config looks like:

```
{"token":"XXXXX", "cache_expiration":86400, "use_mp4":false, "use_subtitles":true}
```

**Comment by OGKevin** [comment]
I dont have remote debugging set up in PyCharm. If not I would have ran the debugger and see whats going on. Hopefully this gives you an idea on what might be happening.

**Comment by OGKevin** [comment]
So the config var is populated correctly, but it seems that dot notation is not working. `config['cache_expiration'] ` does tho. Not sure why dot notation is not working properly on `python2`

**Comment by gpenverne** [comment]
Ok I will add it.
To fix right now on your side, you can call:
PutioMount.set_config('cache_expiration', True)

**Comment by OGKevin** [comment]
I've changed the code to not use the dot notation so it works now. If you like I can make a PR later today 😊

**Comment by gpenverne** [comment]
Yeah with pleasure :)
